name: Deploy Java on Push/Pull Request

on:
  create:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to FTP
        if: github.event_name == 'push'
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          local-dir: '${{ github.workspace }}/target/'
          server-dir: ${{ secrets.SERVER_DIR }}
          exclude: |
            **/classes/**
            **/generated-sources/**
            **/maven-archiver/**
            **/maven-status/**

      - name: SSH into server and start
        if: github.event_name == 'push'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd '${{ secrets.SERVER_DIR }}'
            ./start.sh
          host: ${{ secrets.HOST }}
          port: 222
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
